# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vucut_kitle.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 609)
        MainWindow.setMinimumSize(QtCore.QSize(391, 609))
        MainWindow.setMaximumSize(QtCore.QSize(391, 609))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-30, -30, 441, 661))
        self.frame.setMinimumSize(QtCore.QSize(391, 611))
        self.frame.setMaximumSize(QtCore.QSize(1000, 1000))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 40, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    font: 14pt \"Century\";\n"
"    color: rgb(204, 56, 19);\n"
"\n"
"}")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setIndent(1)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(90, 170, 71, 21))
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(184, 194, 172);\n"
"    font: 10pt \"Wide Latin\";\n"
"\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(90, 240, 71, 31))
        self.label_3.setStyleSheet("QLabel{\n"
"color: rgb(184, 194, 172);\n"
"    font: 9pt \"Wide Latin\";\n"
"\n"
"}")
        self.label_3.setObjectName("label_3")
        self.lineEdit_kilo = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_kilo.setGeometry(QtCore.QRect(190, 170, 81, 31))
        self.lineEdit_kilo.setStyleSheet("QLineEdit{ \n"
"background-color:rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius: 9px;\n"
"padding: 0 8px;\n"
"selection-background-color: darkgray;\n"
"font-size: 16px;}\n"
"QLineEdit:focus { \n"
"background-color:rgb(222, 222, 222);}\n"
"                                        ")
        self.lineEdit_kilo.setMaxLength(3)
        self.lineEdit_kilo.setObjectName("lineEdit_kilo")
        self.lineEdit_boy = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_boy.setGeometry(QtCore.QRect(190, 240, 101, 31))
        self.lineEdit_boy.setStyleSheet("QLineEdit{ \n"
"background-color:rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius: 9px;\n"
"padding: 0 8px;\n"
"selection-background-color: darkgray;\n"
"font-size: 16px;}\n"
"QLineEdit:focus { \n"
"background-color:rgb(222, 222, 222);}")
        self.lineEdit_boy.setMaxLength(3)
        self.lineEdit_boy.setObjectName("lineEdit_boy")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(300, 250, 71, 21))
        self.label_6.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"    \n"
"    font: 10pt \"Palatino Linotype\";\n"
"\n"
"}")
        self.label_6.setObjectName("label_6")
        self.pushButton_hesapla = QtWidgets.QPushButton(self.frame)
        self.pushButton_hesapla.setGeometry(QtCore.QRect(160, 330, 141, 31))
        self.pushButton_hesapla.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(168, 168, 168);\n"
"    font: 12pt \"Elephant\";\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton::hover{\n"
"border-bottom: 2px solid gray;\n"
"border-left: 2px solid gray;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_hesapla.setObjectName("pushButton_hesapla")
        self.label_bilgilendirme = QtWidgets.QLabel(self.frame)
        self.label_bilgilendirme.setGeometry(QtCore.QRect(90, 450, 281, 81))
        self.label_bilgilendirme.setStyleSheet("QLabel{\n"
"background-color: rgb(33, 33, 33);\n"
"    font: 87 10pt \"Arial Black\";\n"
"    color: rgb(229, 229, 229);\n"
"border: 2px solid gray;\n"
"border-radius: 9px;\n"
"}")
        self.label_bilgilendirme.setObjectName("label_bilgilendirme")
        self.pushButton_temizle = QtWidgets.QPushButton(self.frame)
        self.pushButton_temizle.setGeometry(QtCore.QRect(160, 380, 141, 31))
        self.pushButton_temizle.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(168, 168, 168);\n"
"    font: 12pt \"Elephant\";\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton::hover{\n"
"border-bottom: 2px solid gray;\n"
"border-left: 2px solid gray;\n"
"}\n"
"\n"
"")
        self.pushButton_temizle.setObjectName("pushButton_temizle")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(280, 170, 71, 31))
        self.label_7.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"    \n"
"    font: 10pt \"Palatino Linotype\";\n"
"\n"
"}")
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "VUCUT KİTLE ENDEKSİ HESAPLAMA"))
        self.label_2.setText(_translate("MainWindow", "Kilo:"))
        self.label_3.setText(_translate("MainWindow", "BOY:"))
        self.label_6.setText(_translate("MainWindow", "cm"))
        self.pushButton_hesapla.setText(_translate("MainWindow", "HESAPLA"))
        self.label_bilgilendirme.setText(_translate("MainWindow", "Bilgilendirme..."))
        self.pushButton_temizle.setText(_translate("MainWindow", "TEMİZLE"))
        self.label_7.setText(_translate("MainWindow", "kg"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
